title: Jordan Howard # your name (or website title) here
logo: "/images/me.jpg?raw=true"
<a href="https://www.linkedin.com/in/jordan-howard-39386813b/">View My LinkedIn Profile</a> 
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

