title: Jordan Howard # your name (or website title) here
logo: "/images/me.jpg?raw=true"

description: Motivated division 1 student-athlete with a background in Industrial Engineering and Engineering Management education. Well versed in data analytics, visualization and modeling, sales, manufacturing, programming, supply chain analysis, systems engineering, and project management. Accomplished in leading teams and collaborating with others to complete projects.
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

